version: "3.3"

services:
  gold-mule:
    build: ./docker/
    container_name: gold-mule
    env_file:
      - ./docker/.env
    working_dir: /gold-mule/
    volumes: 
      - ./app/:/gold-mule/
    # command: python /gold-mule/src/get-historical-data_01.py
    tty: true
